language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

services:
  - mysql

before_script:
  - mysql -u root -e 'create database laravelblocker;'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - composer create-project --prefer-dist laravel/laravel laravelblocker
  - cp .env.travis laravelblocker/.env
  - cd laravelblocker
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload
  - composer require vildanbina/laravel-blocker
  - php artisan key:generate
  - php artisan vendor:publish --provider="vildanbina\LaravelBlocker\LaravelBlockerServiceProvider"
  - php artisan make:auth
  - composer dump-autoload
  - php artisan clear-compiled
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache
  - php artisan migrate
  - php artisan db:seed
